### ISSUE TITLE
Script doesn't fetch some pages

### ISSUE THREAD

**Issue by asakura42** [KevCui/opensubtitles-dl#2]
For example, this occurs when you run `./opensubtitles-dl.sh -n shingeki -l spa` and select `[2560140] Attack on Titan (TV Series 2013–2023) - IMDb`

It seems it doesn't correctly parses links such this: https://www.opensubtitles.org/en/ssearch/sublanguageid-spa/idmovie-151586

**Comment by KevCui** [comment]
Hey @asakura42, I see, TV series page structure has been changed. I need check if the script can be easily updated or not.

**Comment by KevCui** [comment]
@asakura42  Ok, so I didn't implement code to search on TV series page. Instead, I picked a quick and lazy way...

In order to get the subtitle for certain episode, you need type season number and episode number together after the title name, for example, let's say you want to download Spanish subtitle of `Attack on Titan` season 2 episode 1, enter command:

`./opensubtitles-dl.sh -n 'shingeki s02e01' -l spa`

Then in `fzf` prompt, choose `[4228718] "Attack on Titan" Beast Titan...` . Yes, you have to know the episode name in order to make the right choice.
